### ISSUE TITLE
Is this extension usable with ShareLink?

### ISSUE THREAD

**Issue by markushx** [RickeyBoy/ScreenshotableView#2]
I would like to share the screenshot with [ShareLink](https://developer.apple.com/documentation/swiftui/sharelink).

How could this be integrated?

**Comment by RickeyBoy** [comment]
YES.

### Implement your view and store your image
```
ScreenshotableView(shotting: $shotting) { screenshot in
    self.screenshot = Image(uiImage: screenshot)
} content: { style in
    Content(style: style)
}
```

### use ShareLink with image:
`ShareLink(item: self.screenshot, preview: SharePreview("title", image: self.screenshot))`

**Comment by markushx** [comment]
How is $shotting toggled from the ShareLink? I am only getting an empty image in the preview.

**Comment by RickeyBoy** [comment]
I've pushed new code that implement Sharing part. I use `UIActivityViewController` instead of `ShareLink`. 

You can check with `ShareScreenshotView` file. Enjoy demo 🎉

**Comment by supercosition** [comment]
@StateObject var sasVM = SaveAndShareViewModel().    << Can not find SaveAndShareViewModel() in scope
when i try to use in my project

**Comment by RickeyBoy** [comment]
> [@StateObject](https://github.com/StateObject) var sasVM = SaveAndShareViewModel(). << Can not find SaveAndShareViewModel() in scope when i try to use in my project

You have to create an ObservableObject in you project. You can refer to `SuppotSaveAndShareViewModifier.swift` file in the demo project. @supercosition :)
