### ISSUE TITLE
Screenshot add gray color !

### ISSUE THREAD

**Issue by X901** [RickeyBoy/ScreenshotableView#3]
Hi, 
my view is image and it's white color
when I take the screen shoot and check the image, I notice there is gray color cover the whole screen !
also the quailty reduced
how can I remove it and keep the quailty of the image?
I want to save the image without add any color layer above it or reduce the image quailty !

**Comment by RickeyBoy** [comment]
Could you plz provide your related code? I'm not sure what makes your quality loss.
