### ISSUE TITLE
老哥 动态刷新后的view好像不行

### ISSUE THREAD

**Issue by lixinhao2333** [RickeyBoy/ScreenshotableView#6]
比如我现在有个view 点击button之后才加载在页面上
然后这个新加载的 截图不到

**Comment by RickeyBoy** [comment]
> 比如我现在有个view 点击button之后才加载在页面上 然后这个新加载的 截图不到

理论上加载后再截的图就可以，你有代码的话可以贴一下我试试

**Comment by lixinhao2333** [comment]
在解决了 感谢

**Comment by lixinhao2333** [comment]
引用 EnvironmentObject 变量的时候 截图就会报错 
你那边看看会不会 感谢

**Comment by RickeyBoy** [comment]
> 引用 EnvironmentObject 变量的时候 截图就会报错 你那边看看会不会 感谢

我看了下好像没问题，你报什么错？

**Comment by lixinhao2333** [comment]
用spm会报错，我就把整个拖进去项目里，然后改了一下，就行了
